import fs from 'fs';
import os from 'os';
import path from 'path';

import { config as serverConfig } from '../config/config.js';
import { logger } from '../utils/logger.js';

// svtplay-dl has no `--config <path>` flag; it looks up `svtplay-dl.yaml` in
// (1) cwd, (2) $XDG_CONFIG_HOME/svtplay-dl, (3) ~/.config/svtplay-dl,
// (4) ~/.svtplay-dl.yaml. We write to (3): in Docker that's /root, with no
// pre-existing config to clobber. On dev machines we refuse to overwrite a
// file that lacks our marker header.
const MARKER = '# Auto-generated by svtplay-dl-webui — manual edits will be overwritten.';

function configPath(): string {
  return path.join(os.homedir(), '.config', 'svtplay-dl', 'svtplay-dl.yaml');
}

function yamlString(value: string): string {
  // Quote everything so braces, colons, and special chars in templates and
  // proxy URLs survive YAML parsing untouched.
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

function buildYaml(): string {
  const lines: string[] = [MARKER];
  lines.push(`path: ${yamlString(serverConfig.downloadOutputDir)}`);
  lines.push(`filename: ${yamlString(serverConfig.svtplaydlFilenameTemplate)}`);
  if (serverConfig.svtplaydlProxy) {
    lines.push(`proxy: ${yamlString(serverConfig.svtplaydlProxy)}`);
  }
  return lines.join('\n') + '\n';
}

export function writeSvtplayDlConfig(): void {
  const target = configPath();
  const dir = path.dirname(target);

  if (fs.existsSync(target)) {
    try {
      const head = fs.readFileSync(target, 'utf8').split('\n', 1)[0] ?? '';
      if (head.trim() !== MARKER) {
        logger.warn(
          'Existing svtplay-dl config not auto-generated; refusing to overwrite. ' +
            'Move it aside or delete it to let svtplay-dl-webui manage settings.',
          { path: target },
        );
        return;
      }
    } catch (err) {
      logger.warn('Failed to inspect existing svtplay-dl config; skipping write', {
        path: target,
        error: (err as Error).message,
      });
      return;
    }
  }

  try {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    fs.writeFileSync(target, buildYaml(), { mode: 0o600 });
    logger.info('Wrote svtplay-dl config', { path: target });
  } catch (err) {
    logger.warn('Failed to write svtplay-dl config', {
      path: target,
      error: (err as Error).message,
    });
  }
}
